# Generated by Django 5.1.1 on 2025-03-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_API", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="supplier_name",
            new_name="name",
        ),
    ]
